version: '3.8'

services:
  rtmp-rtsp-converter:
    build: .
    container_name: rtmp-rtsp-converter
    ports:
      # RTSP output ports - adjust as needed
      - "8554:8554"
      - "8555:8555"
      - "8556:8556"
      - "8557:8557"
      - "8558:8558"
    volumes:
      - ./streams.json:/app/streams.json:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - rtmp-rtsp-network

  # Optional: RTMP test server for testing
  rtmp-server:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-test-server
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rtmp-rtsp-network
    profiles:
      - testing

networks:
  rtmp-rtsp-network:
    driver: bridge