version: '3.8'

services:
  rtmp-rtsp-converter:
    build: .
    container_name: rtmp-rtsp-converter
    ports:
      - "5000:5000"     # Flask or web dashboard
      - "8554:8554"     # Main RTSP output
      - "1935:1935"     # Optional RTMP ingest
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./streams.json:/app/streams.json:ro
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - rtmp-rtsp-network

  # Optional RTMP test server for development
  rtmp-server:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-test-server
    ports:
      - "1936:1935"     # External RTMP test input
      - "8080:80"       # Web interface for test server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rtmp-rtsp-network
    profiles:
      - testing         # Only starts when `--profile testing` is used

networks:
  rtmp-rtsp-network:
    driver: bridge
